// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectManagementSystem.Models.EFModels;

public partial class File
{
    public int FileId { get; set; }

    public int TaskId { get; set; }

    public string FileName { get; set; }

    public string FilePath { get; set; }

    public int UploadedById { get; set; }

    public DateTime? UploadedAt { get; set; }

    public virtual Task Task { get; set; }

    public virtual TeamMember UploadedBy { get; set; }
}