// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectManagementSystem.Models.EFModels;

public partial class Notification
{
    public int NotificationId { get; set; }

    public int MemberId { get; set; }

    public int TaskId { get; set; }

    public string Message { get; set; }

    public bool? IsRead { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual TeamMember Member { get; set; }

    public virtual Task Task { get; set; }
}