// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectManagementSystem.Models.EFModels;

public partial class Project
{
    public int ProjectId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public int OwnerId { get; set; }

    public string Status { get; set; }

    public virtual ProjectManager Owner { get; set; }

    public virtual ICollection<Task> Tasks { get; set; } = new List<Task>();
}