// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectManagementSystem.Models.EFModels;

public partial class TaskAssignment
{
    public int AssignmentId { get; set; }

    public int TaskId { get; set; }

    public int MemberId { get; set; }

    public DateTime? AssignedDate { get; set; }

    public virtual TeamMember Member { get; set; }

    public virtual Task Task { get; set; }
}