// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectManagementSystem.Models.EFModels;

public partial class Task
{
    public int TaskId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public int AssignedToId { get; set; }

    public int ProjectId { get; set; }

    public DateTime DueDate { get; set; }

    public string Priority { get; set; }

    public virtual TeamMember AssignedTo { get; set; }

    public virtual ICollection<File> Files { get; set; } = new List<File>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual Project Project { get; set; }

    public virtual ICollection<TaskAssignment> TaskAssignments { get; set; } = new List<TaskAssignment>();
}